-- AdminSpec.md section 5.1 — the exact 32 permission keys. Safe to re-run.
insert into permissions (key, description) values
  ('attendance.mark',              'Mark daily attendance for a class'),
  ('attendance.view_board',        'View the class/staff marking-status board'),
  ('attendance.remind',            'Send a reminder to unmarked classes in scope'),
  ('attendance.amend_locked',      'Edit attendance after its edit window has closed'),
  ('attendance.early_leave',       'Record a student leaving before the school day ends'),
  ('attendance.mark_staff',        'Mark another staff member''s daily attendance'),
  ('attendance.reopen_staff',      'Reopen a past date''s staff attendance for editing by others'),
  ('student.view_basic',           'View a student''s name, class and photo'),
  ('student.view_full',            'View a student''s full profile'),
  ('student.view_benefits',        'View a student''s benefit records'),
  ('student.edit',                 'Edit a student''s record'),
  ('student.view_guardian_contact','View guardian phone numbers'),
  ('marks.enter',                  'Enter marks for a class and subject'),
  ('marks.review',                 'Review submitted mark sheets'),
  ('marks.reopen',                 'Reopen a submitted mark sheet for editing'),
  ('staff.view_directory',         'View the staff directory'),
  ('staff.view_full',              'View a staff member''s full profile'),
  ('staff.manage',                 'Create and edit staff accounts'),
  ('staff.assign_responsibility',  'Assign a responsibility or duty to staff'),
  ('leave.request',                'Request leave for oneself'),
  ('leave.approve',                'Approve or reject leave requests'),
  ('leave.view_balances',          'View leave balances'),
  ('cover.assign',                 'Assign a cover teacher to a class'),
  ('announcement.publish_all',     'Publish an announcement to the whole school'),
  ('announcement.publish_section', 'Publish an announcement to a section'),
  ('inventory.view',               'View inventory items and stock levels'),
  ('inventory.manage',             'Record inventory movements and manage items'),
  ('event.manage',                 'Create and edit school events'),
  ('diary.manage',                 'Create and edit school diary entries'),
  ('calendar.manage',              'Edit the academic calendar'),
  ('analytics.view',               'View analytics dashboards'),
  ('report.export',                'Export reports as spreadsheets'),
  ('account.manage',               'Create and manage user accounts and role assignments'),
  ('audit.view',                   'View the audit log')
on conflict (key) do update set description = excluded.description;
